
language: r
r:
    - oldrel
    - release
    - devel
os:
    - linux

cache: packages

warnings_are_errors: true

# Handle git submodules yourself from http://stackoverflow.com/questions/15674064/github-submodule-access-rights-travis-ci
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

# for code coverage
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
