---
title: "Grip Project Template"
author: "Jonathan Keane"
date: "May 3, 2016"
output: html_document
---

## test

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r action}
actionCat.fit <- lme4::lmer(maxGrip~stickcmScaled*fins + (1+stickcmScaled*fins|obsisSubj), data[["action"]])

summary(actionCat.fit)
mocapGrip:::CoefficientPlot(list(actionCat.fit))
mocapGrip:::ggCaterpillar(lme4::ranef(actionCat.fit, condVar = TRUE))

ggplot(mocapGrip:::pred(actionCat.fit)) + aes(x=stickcmScaled+8, y=maxGrip, ymin=plo, ymax=phi, group=fins, color=fins) + geom_pointrange(position = position_dodge(width=0.5)) + labs(title = "Model predictions for maximum grip") 
```

```{r estimation}
estimation.fit <- lme4::lmer(meanGrip~stickcmScaled*fins + (1+stickcmScaled*fins|obsisSubj), data[["estimation"]])

summary(estimation.fit)
mocapGrip:::CoefficientPlot(list(estimation.fit))
mocapGrip:::ggCaterpillar(lme4::ranef(estimation.fit, condVar = TRUE))

ggplot(mocapGrip:::pred(estimation.fit)) + aes(x=stickcmScaled+8, y=meanGrip, ymin=plo, ymax=phi, group=fins, color=fins) + geom_pointrange(position = position_dodge(width=0.5)) + labs(title = "Model predictions for maximum grip") 

```
